name = "medium-app"
main = "src/index.ts"
compatibility_date = "2024-10-13"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzAwOWNjZGYtMTNjNi00MTgzLTgyZGMtMGMyMmFiYzc1ZjMxIiwidGVuYW50X2lkIjoiZmZiMTI4ZDhlZTQ2Y2Y2NGU4NWI1NjZkMzc0YTZmZDgyYjIxYjZhNzhlNGRkNjAzNzkzNjdkNGIyODBjZjkyNiIsImludGVybmFsX3NlY3JldCI6ImM2NzIxM2E0LWI4ZjEtNDkyYi04ODVkLWZiMmMxMTY5MWY1MSJ9.CfmgC0IBinN4F5c6JvpI-LELuWF6M-sMumBDFSnNqB8"
